company_symbols = {
    "apple": "AAPL",
    "microsoft": "MSFT",
    "amazon": "AMZN",
    "alphabet": "GOOGL",
    "facebook": "FB",
    "tesla": "TSLA",
    "nvidia": "NVDA",
    "walmart": "WMT",
    "johnson & johnson": "JNJ",
    "visa": "V",
    "procter & gamble": "PG",
    "mastercard": "MA",
    "jpmorgan chase": "JPM",
    "adobe": "ADBE",
    "paypal holdings": "PYPL",
    "intel": "INTC",
    "netflix": "NFLX",
    "home depot": "HD",
    "cisco systems": "CSCO",
    "verizon communications": "VZ",
    "pfizer": "PFE",
    "mcdonald's": "MCD",
    "salesforce.com": "CRM",
    "at&t": "T",
    "coca-cola": "KO",
    "ibm": "IBM",
    "abbott laboratories": "ABT",
    "accenture": "ACN",
    "pepsico": "PEP",
    "merck": "MRK",
    "honeywell international": "HON",
    "medtronic": "MDT",
    "nike": "NKE",
    "abbvie": "ABBV",
    "oracle": "ORCL",
    "goldman sachs group": "GS",
    "general electric": "GE",
    "3m": "MMM",
    "berkshire hathaway": "BRK.A",
    "walt disney": "DIS",
    "costco wholesale": "COST",
    "caterpillar": "CAT",
    "exxon mobil": "XOM",
    "bristol-myers squibb": "BMY",
    "unitedhealth group": "UNH",

}
